{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "expertise-api.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "expertise-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: pgbouncer
      port: 6432
      targetPort: 6432
  selector:
    {{- include "expertise-api.postgresSelectorLabels" . | nindent 4 }}
{{- end }}
