#!/usr/bin/env bash
#
# brew-install-postgres17.sh — install PostgreSQL 17 + pgvector via Homebrew for the
# macOS install-smoke CI jobs, self-healing a corrupt pre-cached bottle.
#
# BEST-EFFORT heal for the macOS install-smoke jobs. The `postgresql@17` bottle on
# current macOS runner images fails at service start with:
#     initdb: error: file "/opt/homebrew/share/postgresql@17/postgres.bki" does not exist
# Diagnosed as an upstream Homebrew bug (share-dir path mismatch on a keg-only
# formula; the file exists in the keg but initdb/server look in the unpopulated
# top-level prefix). Tracked in #366 — the three macOS smoke jobs are
# `continue-on-error: true` until it is fixed, so this heal not landing does not
# block merges. Remove the continue-on-error (and revisit this heal) when #366 closes.
#
# The two heals below are retained because they DO fix adjacent variants and cost
# nothing when they no-op:
#   1. Source rebuild — for a genuinely-absent postgres.bki (regenerated by `make`).
#   2. Force-link — relinks a keg-only keg into the prefix (no-op if already linked).
#
# `postgresql@17` is keg-only, so its bin/ is exported via GITHUB_PATH for
# subsequent workflow steps. Shared by all three macOS smoke jobs (ci.yml x2 +
# install-smoke-from-release.yml) so the heal lives in one place.
#
# Exit codes: 0 ok · 1 postgres.bki genuinely absent even after source rebuild.

set -euo pipefail

log() { printf '[brew-pg17] %s\n' "$*"; }

# Path to postgres.bki inside the keg, or empty if genuinely absent.
find_bki() { find "$(brew --prefix postgresql@17)/share" -name postgres.bki 2>/dev/null | head -1; }

brew update >/dev/null

# Tolerate a non-zero exit: the keg-only path mismatch fails the formula's
# post_install initdb, but the file is present and the link/rebuild below is the
# real fix. Install postgresql@17 BEFORE pgvector so pgvector lands in a
# repaired keg.
brew install postgresql@17 || log "postgresql@17 install returned non-zero (keg-only post_install initdb); repairing"

if [ -z "$(find_bki)" ]; then
  log "postgres.bki genuinely absent from keg — rebuilding from source"
  HOMEBREW_NO_INSTALL_FROM_API=1 brew reinstall --build-from-source postgresql@17
  [ -n "$(find_bki)" ] || { echo "::error::postgres.bki still absent after source rebuild"; exit 1; }
  log "source rebuild OK"
fi

# Force-link the keg-only formula so $(brew --prefix)/share/postgresql@17 (where
# initdb and the server look) resolves to the keg's share. --overwrite yields to
# postgresql@17 over any preinstalled postgresql@14 links (the smoke targets 17).
log "force-linking keg-only postgresql@17 so initdb finds its share dir"
brew link --overwrite --force postgresql@17

brew install pgvector || log "pgvector install returned non-zero; the Start step verifies CREATE EXTENSION"

# Export the keg-only bin/ for later steps (GITHUB_PATH is the cross-step channel).
if [ -n "${GITHUB_PATH:-}" ]; then
  echo "$(brew --prefix postgresql@17)/bin" >> "$GITHUB_PATH"
fi

log "postgresql@17 + pgvector ready"
